# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Projects
    url: '#projects'
    weight: 80
  - name: Talks
    url: '#talks'
    weight: 70
  - name: Publications
    url: '#featured'
    weight: 20
  - name: Experience
    url: '#experience'
    weight: 30
  - name: Posts
    url: '#posts'
    weight: 60
  - name: Experience
    url: '#experience'
    weight: 40
  - name: Accomplishments
    url: '#accomplishments'
    weight: 50
